development:
  adapter: postgresql
  encoding: unicode
  database: development_foodrder
  host: localhost
  pool: 5
  username: luis
  password: rodge24

test:
  adapter: postgresql
  encoding: unicode
  database: test_foodrder
  host: localhost
  pool: 5
  username: luis
  password: rodge24

production:
  adapter: postgresql
  encoding: unicode
  database: production_foodrder
  host: localhost
  pool: 5
  username: luis
  password: rodge24